# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea693bca5b2fd009fbe5484a25af802bd51c0d47139865db90bcb4fb6c0482de2f90654373d9799eb48cbb64858256c865f7275b2422c940d4f67495e6153de5

test:
  secret_key_base: 6264cbf7a0a47c722cf7273952c23846fd919425d49f542377aa2ff7cdf05b2f1e99a3d16440070320c837b3be00a27f225881d7cf46e5f919ef7a347d155d8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
